AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 Bucket for Lambdas
Parameters:
  # Ownership
  Owner:
    Type: String
    Default: FirstName LastName
  Project:
    Type: String
    Default: S3 Backup Bucket Creation
  DeleteAfter:
    Type: String
    Default: 30/06/2020
  # Deployment
  BucketName:
    Type: String
  PreviousLifeCycle:
    Type: Number
    Default: 30

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
         - Id: !Join [ "", [ "Delete Previous > ", !Ref PreviousLifeCycle, " Days" ] ]
           NoncurrentVersionExpirationInDays: !Ref PreviousLifeCycle
           Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
        - Key: DeleteAfter
          Value: !Ref DeleteAfter
 
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
        -
          Sid: "DenyIncorrectEncryptionHeader"
          Effect: Deny
          Principal: "*"
          Action:
            - "s3:PutObject"
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Condition:
            StringNotEquals:
              s3:x-amz-server-side-encryption:
                - "AES256"
                - "aws:kms"
        -
          Sid: "DenyUnencryptedObjectUploads"
          Effect: Deny
          Principal: "*"
          Action:
            - "s3:PutObject"
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Condition:
            "Null":
              s3:x-amz-server-side-encryption: "true"
 
Outputs:
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref BucketName
  PreviousLifeCycle:
    Description: Previous Life Cycle
    Value: !Ref PreviousLifeCycle

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    -
      Label:
        default: Ownership
      Parameters:
        - Owner
        - Project
        - DeleteAfter
    -
      Label:
        default: Deployment
      Parameters:
        - BucketName
        - PreviousLifeCycle
    ParameterLabels:
      # Ownership
      Owner:
        default: Contact Owner
      Project:
        default: ASV
      DeleteAfter:
        default: CMDB Environment
      # Deployment
      BucketName:
        default: Bucket Name
      PreviousLifeCycle:
        default: Previous LifeCycle (Days)
